# Generated by Django 4.1.2 on 2022-10-19 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_feeding"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeding",
            name="cat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.cat",
            ),
        ),
    ]
